### ISSUE TITLE
Use decodable 

### ISSUE THREAD

**Issue by raul9318** [bently93/Doctors#1]
Speciality.swift

import Foundation
import RealmSwift

class SpecList: Decodable {
    let list: [Speciality]
    
    enum CodingKeys: String, CodingKey {
        case list = "SpecList"   
    }
}

class Speciality: Object, Decodable {
    @objc dynamic var id = 0
    @objc dynamic var name = ""
    @objc dynamic var alias = ""

    enum CodingKeys: String, CodingKey {
        case id = "Id"
        case name = "Name"
        case alias = "Alias"
    }
}

RestApi.swift -> getSpeciality()

case .success:

if let data = response.data {
    let specs = try? JSONDecoder().decode(SpecList.self, from: data)
    observer.onNext(specs?.list ?? [])
} else {
    observer.onError(APIError.badRequest)
}
                            
return

**Comment by bently93** [comment]
Close in 0bf1027b07bc7c85a54e21028540221b48c4c899
